#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
start_script="${project_dir}/start_dashboard.sh"
config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"
state_dir="${config_home}/cyberdash-red-kiosk"
desktop_entry="${config_home}/autostart/cyberdash-red.desktop"

if [[ ! -x "${start_script}" ]]; then
    printf 'Startup script is not executable: %s\n' "${start_script}"
    printf 'Run: chmod +x start_dashboard.sh install_kiosk_startup.sh\n'
    exit 1
fi

if [[ "${start_script}" =~ [[:space:]\'] ]]; then
    printf 'The project path cannot contain spaces or single quotes in kiosk mode.\n'
    exit 1
fi

if [[ -f "${state_dir}/installed" ]]; then
    printf 'Cyberdash kiosk startup is already installed.\n'
    printf 'Run ./disable_kiosk_startup.sh before installing it again.\n'
    exit 1
fi

session_kind="${CYBERDASH_SESSION_KIND:-}"
if [[ -z "${session_kind}" ]]; then
    if pgrep -x labwc >/dev/null 2>&1; then
        session_kind="labwc"
    elif pgrep -x openbox >/dev/null 2>&1 \
        || [[ "${XDG_CURRENT_DESKTOP:-}" == *LXDE* ]]; then
        session_kind="lxde"
    elif pgrep -x wayfire >/dev/null 2>&1; then
        session_kind="wayfire"
    fi
fi

case "${session_kind}" in
    labwc)
        session_autostart="${config_home}/labwc/autostart"
        ;;
    lxde)
        lxde_profile="${CYBERDASH_LXDE_PROFILE:-}"
        if [[ -z "${lxde_profile}" ]]; then
            if [[ -d "${config_home}/lxsession/LXDE-pi" ]] \
                || [[ -d /etc/xdg/lxsession/LXDE-pi ]]; then
                lxde_profile="LXDE-pi"
            else
                lxde_profile="LXDE"
            fi
        fi
        session_autostart="${config_home}/lxsession/${lxde_profile}/autostart"
        ;;
    wayfire)
        printf 'Wayfire was detected, but this kiosk installer does not modify wayfire.ini.\n'
        printf 'Run ./install_autostart.sh for a safe desktop autostart instead.\n'
        exit 1
        ;;
    *)
        printf 'Could not identify the active desktop startup system.\n'
        printf 'Detected desktop: %s\n' "${XDG_CURRENT_DESKTOP:-unknown}"
        printf 'Run ./install_autostart.sh for a safe desktop autostart instead.\n'
        exit 1
        ;;
esac

mkdir -p "$(dirname -- "${session_autostart}")" "${state_dir}"

if [[ -f "${session_autostart}" ]]; then
    cp -a "${session_autostart}" "${state_dir}/original-session-autostart"
else
    : > "${state_dir}/no-original-session-autostart"
fi

if [[ -f "${desktop_entry}" ]]; then
    mv "${desktop_entry}" "${state_dir}/normal-autostart.desktop"
fi

printf '%s\n' "${session_kind}" > "${state_dir}/session-kind"
printf '%s\n' "${session_autostart}" > "${state_dir}/autostart-path"

session_runner="${state_dir}/run-dashboard-session.sh"
printf '%s\n' \
    '#!/usr/bin/env bash' \
    '# Paint the X11 root window black before Python and Kivy start.' \
    'if command -v xsetroot >/dev/null 2>&1; then' \
    '    xsetroot -solid black >/dev/null 2>&1 || true' \
    'fi' \
    '# Restart after a crash; a clean exit such as Esc remains black.' \
    'while true; do' \
    "    env CYBERDASH_START_DELAY=0 '${start_script}'" \
    '    dashboard_status=$?' \
    '    [[ "${dashboard_status}" -eq 0 ]] && exit 0' \
    '    sleep 1' \
    'done' \
    > "${session_runner}"
chmod 700 "${session_runner}"

temporary_file="$(mktemp "$(dirname -- "${session_autostart}")/autostart.cyberdash.XXXXXX")"
trap 'rm -f "${temporary_file}"' EXIT

if [[ "${session_kind}" == "labwc" ]]; then
    printf '%s\n' \
        '#!/bin/sh' \
        '# Generated by Cyberdash Red. This intentionally starts no desktop panel.' \
        "exec '${session_runner}'" \
        > "${temporary_file}"
    chmod 700 "${temporary_file}"
else
    printf '%s\n' \
        '# Generated by Cyberdash Red for Raspberry Pi LXDE/Openbox.' \
        '# Omitting lxpanel and pcmanfm prevents the desktop from flashing.' \
        "${session_runner}" \
        > "${temporary_file}"
    chmod 600 "${temporary_file}"
fi

mv "${temporary_file}" "${session_autostart}"
: > "${state_dir}/installed"
trap - EXIT

printf 'Cyberdash fast kiosk startup is installed for: %s\n' "${session_kind}"
printf 'Startup file: %s\n' "${session_autostart}"
printf 'Saved recovery state: %s\n' "${state_dir}"
printf '\nBefore rebooting, confirm these Raspberry Pi settings:\n'
printf '  1. Boot: Desktop\n'
printf '  2. Desktop Auto Login: On\n'
printf '  3. Splash Screen: On\n'
printf '\nThen reboot with: sudo reboot\n'
printf '\nRecovery: Ctrl+Alt+F2, log in, then run:\n'
printf '  cd %q && ./disable_kiosk_startup.sh\n' "${project_dir}"
