#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
start_script="${project_dir}/start_dashboard.sh"
labwc_dir="${HOME}/.config/labwc"
labwc_autostart="${labwc_dir}/autostart"
state_dir="${HOME}/.config/cyberdash-red-kiosk"
desktop_entry="${XDG_CONFIG_HOME:-${HOME}/.config}/autostart/cyberdash-red.desktop"

if [[ ! -x "${start_script}" ]]; then
    printf 'Startup script is not executable: %s\n' "${start_script}"
    printf 'Run: chmod +x start_dashboard.sh install_kiosk_startup.sh\n'
    exit 1
fi

if [[ "${start_script}" == *"'"* ]]; then
    printf 'The project path cannot contain a single quote in kiosk mode.\n'
    exit 1
fi

if ! command -v labwc >/dev/null 2>&1 \
    && [[ ! -f /etc/xdg/labwc/autostart ]]; then
    printf 'This fast kiosk installer requires the Raspberry Pi OS labwc desktop.\n'
    printf 'Your normal desktop autostart has not been changed.\n'
    printf 'Use ./install_autostart.sh on older X11-based systems.\n'
    exit 1
fi

mkdir -p "${labwc_dir}" "${state_dir}"

if [[ ! -f "${state_dir}/installed" ]]; then
    if [[ -f "${labwc_autostart}" ]]; then
        cp -a "${labwc_autostart}" "${state_dir}/original-labwc-autostart"
    else
        : > "${state_dir}/no-original-labwc-autostart"
    fi

    if [[ -f "${desktop_entry}" ]]; then
        mv "${desktop_entry}" "${state_dir}/normal-autostart.desktop"
    fi
fi

temporary_file="$(mktemp "${labwc_dir}/autostart.cyberdash.XXXXXX")"
trap 'rm -f "${temporary_file}"' EXIT

printf '%s\n' \
    '#!/bin/sh' \
    '# Generated by Cyberdash Red. This intentionally starts no desktop panel.' \
    '# A clean exit (including Esc) leaves the kiosk screen black.' \
    'while true; do' \
    "    env CYBERDASH_START_DELAY=0 '${start_script}'" \
    '    dashboard_status=$?' \
    '    [ "${dashboard_status}" -eq 0 ] && break' \
    '    sleep 1' \
    'done' \
    > "${temporary_file}"

chmod 700 "${temporary_file}"
mv "${temporary_file}" "${labwc_autostart}"
: > "${state_dir}/installed"
trap - EXIT

printf 'Cyberdash fast kiosk startup is installed.\n'
printf 'Saved recovery state: %s\n' "${state_dir}"
printf '\nBefore rebooting, confirm these Raspberry Pi settings:\n'
printf '  1. Boot: Desktop\n'
printf '  2. Desktop Auto Login: On\n'
printf '  3. Splash Screen: On\n'
printf '\nOpen them with: sudo raspi-config\n'
printf 'Then reboot with: sudo reboot\n'
printf '\nRecovery: Ctrl+Alt+F2, log in, then run:\n'
printf '  cd %q && ./disable_kiosk_startup.sh\n' "${project_dir}"
